// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: proto/fuse.proto

package go_fuse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DirLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Полное имя директории
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *DirLocation) Reset() {
	*x = DirLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirLocation) ProtoMessage() {}

func (x *DirLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirLocation.ProtoReflect.Descriptor instead.
func (*DirLocation) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{0}
}

func (x *DirLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type DirObjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Имена каталогов, находящихся в нужной директории
	DirNames []string `protobuf:"bytes,1,rep,name=dirNames,proto3" json:"dirNames,omitempty"`
	// Имена файлов, находящихся в нужной директории
	FileNames []string `protobuf:"bytes,2,rep,name=fileNames,proto3" json:"fileNames,omitempty"`
}

func (x *DirObjects) Reset() {
	*x = DirObjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirObjects) ProtoMessage() {}

func (x *DirObjects) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirObjects.ProtoReflect.Descriptor instead.
func (*DirObjects) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{1}
}

func (x *DirObjects) GetDirNames() []string {
	if x != nil {
		return x.DirNames
	}
	return nil
}

func (x *DirObjects) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type FileName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Полное имя файла
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *FileName) Reset() {
	*x = FileName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileName) ProtoMessage() {}

func (x *FileName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileName.ProtoReflect.Descriptor instead.
func (*FileName) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{2}
}

func (x *FileName) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Url вида https://api.telegram.org/file/bot<token>/<file_path>
	Fileurl string `protobuf:"bytes,1,opt,name=fileurl,proto3" json:"fileurl,omitempty"`
}

func (x *FileUrl) Reset() {
	*x = FileUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUrl) ProtoMessage() {}

func (x *FileUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUrl.ProtoReflect.Descriptor instead.
func (*FileUrl) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{3}
}

func (x *FileUrl) GetFileurl() string {
	if x != nil {
		return x.Fileurl
	}
	return ""
}

type FileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// часть файла в бинарном виде
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileData) Reset() {
	*x = FileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{4}
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id файла, сгенерированный сервером
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FileId) Reset() {
	*x = FileId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileId) ProtoMessage() {}

func (x *FileId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileId.ProtoReflect.Descriptor instead.
func (*FileId) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{5}
}

func (x *FileId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id файла, сгенерированный сервером
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Полное имя файла
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *FileMetaData) Reset() {
	*x = FileMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fuse_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetaData) ProtoMessage() {}

func (x *FileMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetaData.ProtoReflect.Descriptor instead.
func (*FileMetaData) Descriptor() ([]byte, []int) {
	return file_proto_fuse_proto_rawDescGZIP(), []int{6}
}

func (x *FileMetaData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileMetaData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_fuse_proto protoreflect.FileDescriptor

var file_proto_fuse_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0b, 0x44, 0x69, 0x72, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0a, 0x44, 0x69, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x75, 0x72, 0x6c, 0x22, 0x1e, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xfd,
	0x02, 0x0a, 0x0c, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x62, 0x6f, 0x74, 0x12,
	0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x49, 0x6e, 0x44,
	0x69, 0x72, 0x12, 0x14, 0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x44, 0x69, 0x72,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f,
	0x74, 0x67, 0x2e, 0x44, 0x69, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x00, 0x12,
	0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x11, 0x2e,
	0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x10, 0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55,
	0x72, 0x6c, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x11, 0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0f, 0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3f, 0x0a, 0x0c, 0x47, 0x69,
	0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x66, 0x75, 0x73,
	0x65, 0x5f, 0x74, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14,
	0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x44, 0x69, 0x72, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14,
	0x2e, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x67, 0x2e, 0x44, 0x69, 0x72, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x11,
	0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x6f, 0x5f, 0x66, 0x75, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fuse_proto_rawDescOnce sync.Once
	file_proto_fuse_proto_rawDescData = file_proto_fuse_proto_rawDesc
)

func file_proto_fuse_proto_rawDescGZIP() []byte {
	file_proto_fuse_proto_rawDescOnce.Do(func() {
		file_proto_fuse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fuse_proto_rawDescData)
	})
	return file_proto_fuse_proto_rawDescData
}

var file_proto_fuse_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fuse_proto_goTypes = []interface{}{
	(*DirLocation)(nil),   // 0: fuse_tg.DirLocation
	(*DirObjects)(nil),    // 1: fuse_tg.DirObjects
	(*FileName)(nil),      // 2: fuse_tg.FileName
	(*FileUrl)(nil),       // 3: fuse_tg.FileUrl
	(*FileData)(nil),      // 4: fuse_tg.FileData
	(*FileId)(nil),        // 5: fuse_tg.FileId
	(*FileMetaData)(nil),  // 6: fuse_tg.FileMetaData
	(*emptypb.Empty)(nil), // 7: google.protobuf.Empty
}
var file_proto_fuse_proto_depIdxs = []int32{
	0, // 0: fuse_tg.telegram_bot.GetObjectsInDir:input_type -> fuse_tg.DirLocation
	2, // 1: fuse_tg.telegram_bot.GetFileUrl:input_type -> fuse_tg.FileName
	4, // 2: fuse_tg.telegram_bot.UploadFile:input_type -> fuse_tg.FileData
	6, // 3: fuse_tg.telegram_bot.GiveFileName:input_type -> fuse_tg.FileMetaData
	0, // 4: fuse_tg.telegram_bot.CreateDirectory:input_type -> fuse_tg.DirLocation
	0, // 5: fuse_tg.telegram_bot.DeleteObject:input_type -> fuse_tg.DirLocation
	1, // 6: fuse_tg.telegram_bot.GetObjectsInDir:output_type -> fuse_tg.DirObjects
	3, // 7: fuse_tg.telegram_bot.GetFileUrl:output_type -> fuse_tg.FileUrl
	5, // 8: fuse_tg.telegram_bot.UploadFile:output_type -> fuse_tg.FileId
	7, // 9: fuse_tg.telegram_bot.GiveFileName:output_type -> google.protobuf.Empty
	7, // 10: fuse_tg.telegram_bot.CreateDirectory:output_type -> google.protobuf.Empty
	7, // 11: fuse_tg.telegram_bot.DeleteObject:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fuse_proto_init() }
func file_proto_fuse_proto_init() {
	if File_proto_fuse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fuse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirObjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fuse_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fuse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fuse_proto_goTypes,
		DependencyIndexes: file_proto_fuse_proto_depIdxs,
		MessageInfos:      file_proto_fuse_proto_msgTypes,
	}.Build()
	File_proto_fuse_proto = out.File
	file_proto_fuse_proto_rawDesc = nil
	file_proto_fuse_proto_goTypes = nil
	file_proto_fuse_proto_depIdxs = nil
}
